[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "services/user",
    "services/alarm",
    "services/payment",
]
